# Generated by Django 4.2.4 on 2023-09-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd',
            old_name='publiched',
            new_name='published',
        ),
    ]
